name: Evaluate CI Matrix
description: Evaluate all packages, check cache status generate CI matrix and publish comment with the summary

inputs:
  is-initial:
    description: Is this the start of the CI workflow, or the end
    default: 'true'
    required: true
  cachix-cache:
    description: The name of the cachix cache to use
    required: true
  nix-github-token:
    description: GitHub token to add as access-token in nix.conf
    required: true
outputs:
  matrix:
    description: 'Generated Matrix'
    value: ${{ steps.generate-matrix.outputs.matrix }}
  comment:
    description: 'Comment'
    value: ${{ steps.generate-matrix.outputs.comment }}

runs:
  using: "composite"
  steps:
    - name: Install Nix
      uses: cachix/install-nix-action@v31
      with:
        github_access_token: ${{ inputs.GITHUB_TOKEN }}
        extra_nix_config: accept-flake-config = true

    - name: Generate CI Matrix
      id: generate-matrix
      shell: bash
      env:
        IS_INITIAL: ${{ inputs.is-initial }}
        CACHIX_CACHE: ${{ inputs.cachix-cache }}
      run: nix develop .#ci -c ./scripts/ci-matrix.sh

    - name: Upload CI Matrix
      uses: actions/upload-artifact@v4
      with:
        name: matrix-${{ inputs.is-initial == 'true' && 'pre' || 'post' }}.json
        path: .result/matrix-${{ inputs.is-initial == 'true' && 'pre' || 'post' }}.json

    - name: Update GitHub Comment
      uses: marocchino/sticky-pull-request-comment@v2.9.0
      with:
        path: .result/comment.md
