lib: rec {
  supportedVersions = {
    source = builtins.fromJSON (builtins.readFile ./supported-source-versions.json);
  };

  # Combined, version-keyed dub dependency locks (regenerated by the fetcher's
  # in-tree dub-to-nix). Each value is the `{ dependencies = { ... }; }` object
  # buildDubPackage's `dubLock` expects.
  dubLocks = builtins.fromJSON (builtins.readFile ./dub-locks.json);

  getBinaryVersion = null; # unsupported

  getSourceVersion =
    _ourPkgs: version:
    assert builtins.hasAttr version supportedVersions.source;
    assert builtins.hasAttr version dubLocks;
    let
      componentHashes = supportedVersions.source."${version}";
    in
    import ./default.nix (
      {
        inherit version;
        srcSha256 = componentHashes.src;
        dubLock = dubLocks."${version}";
      }
      // lib.optionalAttrs (componentHashes ? rev) { inherit (componentHashes) rev; }
    );
}
