name: CI

on:
  workflow_dispatch:
  merge_group:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Nix:
    strategy:
      fail-fast: false
      matrix:
        experimental: [false]
        os: [ ubuntu-latest, macos-12 ]
        pkg:
          - dmd
          - ldc
          - dub
        include:
          - { experimental: true, pkg: ldc, os: macos-12 }
        exclude:
          - { experimental: false, pkg: ldc, os: macos-12 }

    name: ${{ matrix.pkg }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}

    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v9

      - name: Run the Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v2

      - uses: cachix/cachix-action@v14
        with:
          name: ${{ vars.CACHIX_CACHE }}
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Build ${{ matrix.job_name }}
        run: nix build -L --json --no-link '.#${{ matrix.pkg }}'
