name: "Update Dub Package Database"

on:
  # Enable option to manually run the action:
  workflow_dispatch:

  # Run every Sunday at 00:00:
  schedule:
    - cron: 0 0 * * 0

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run `dump_dlang_pkgs.d`
        id: update-lockfile
        run: COMMIT_MSG=$(./scripts/commit_flake_update.bash | tee /dev/tty))

      - uses: tibdex/github-app-token@v2.1.0
        id: generate-token
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ steps.generate-token.outputs.token }}
          title: 'Update Dub Package Database'
          commit-message: ${{ env.COMMIT_MSG }}
          branch: 'create-pull-request/update-dub-package-database'
          delete-branch: true
          branch-suffix: timestamp
          add-paths: flake.lock
